### ISSUE TITLE
Installation instruction for the dependencies

### ISSUE THREAD

**Issue by RicherMans** [Marvin182/rir-database#3]
Hey there, 
I just came across your repository, and wanted to thank you for compiling this code.

I personally just have one problem: dependencies. Your code is dependent on quite a lot of libraries, which are not in the readme. Could I adjust that?

**Comment by Marvin182** [comment]
You are right, dependencies should be listed in the README. I updated the README.

Liste of packages is:
numpy
soundfile
patool
scipy
scikits.samplerate

**Comment by RicherMans** [comment]
Vielen Dank!
